export const DATE = 'YYYY-MM-DD';
export const DATE_SLASH = 'YYYY/MM/DD';
export const DATE_TIME = 'YYYY-MM-DD HH:mm';
export const DATE_TIME_WITH_SLASH = 'YYYY/MM/DD';
export const JDATE = 'jYYYY-jMM-jDD';
export const JDATE_SLASH = "jYYYY/jMM/jDD";
export const JDATE_TIME = 'YYYY-MM-DD HH:mm';
export const JDATE_TIME_WITH_SLASH = 'jYYYY/jMM/jDD';
export const JDATE_WITH_SLASH = 'jYYYY/jMM/jDD';
